name: ESLint

on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install ESLint
      run: npm i -g eslint
    - name: Lint
      run: eslint --ext .ts,.js,.vue --ignore-path .gitignore .
