name: ESLint

on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Use Cache # for optimize Install Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-eslint-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
        restore-keys: |
          ${{ runner.os }}-eslint-
    - name: Install Dependencies
      run: npm ci # Do not use "npm install" to update package-lock.json.
    - name: Lint
      run: npm run lint
