name: Import Song

on:
  push:
    branches:
      - 'master'
    paths:
      - 'song-info/**'
      - '.github/workflows/import-song.yml'

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Use Cache # for optimize Install Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        run: npm ci
      - name: Unit Test with Jest
        run: npm test
      - name: Create master JSON Files & Increment Firestore Version
        run: npm start
        env:
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_SDK_PROJECT_ID }}
      - name: Prettier Created JSON
        run: npx prettier -l "./static/*.json" --write
      - name: Push Created Json Files
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name ${GITHUB_ACTOR}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git add -A
          git commit -m "feat(song): update master json from ${GITHUB_SHA}"
          git push
