name: Node CI

on:
  push:
    paths:
      - '**.*'
      - '!**.md' # Exclude Markdown
  pull_request:
    paths:
      - '**.*'
      - '!**.md' # Exclude Markdown

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10]
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Java 9
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.x'
        architecture: x64
    - name: Use Cache # for optimize Install Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
    - name: Install Dependencies
      run: npm ci # Do not use "npm install" to update package-lock.json.
    - name: Install firestore Emulator
      run: |
        npm i -g firebase-tools
        npx firebase setup:emulators:firestore
    - name: Build with Nuxt
      run: npm run build
    - name: Run firestore Emulator & Test with Jest
      run: npx firebase emulators:exec --only firestore "npm run test:all -- --ci"
    - name: Report Code Coverage to codecov
      if: matrix.node-version == 10
      run: npx codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Archive Production Artifact
      if: contains(github.ref, 'tags/v') && matrix.node-version == 10 # works only version tagged
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: dist

  deploy:
    name: Deploy
    needs: [build]
    if: contains(github.ref, 'tags/v') # works only version tagged
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Production Artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: dist
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install Firebase tool
      run: npm install -g firebase-tools
    - name: Deploy to Firebase
      run: npx firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
