name: Node CI

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!**.md' # Exclude Markdown
  pull_request:
    paths:
      - '**'
      - '!**.md' # Exclude Markdown

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
        include:
          - node-version: 12
            is-main: true
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      # Cache
      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Clean npm cache directory
        run: npm cache clear --force
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci
      - name: Install firestore Emulator
        run: |
          npm i -g firebase-tools
          npx firebase setup:emulators:firestore
      - name: Lint
        run: npm run lint
      - name: Build (Staging)
        run: npm run build
      - name: Run firestore Emulator & Test with Jest
        run: firebase emulators:exec --only firestore "npm run test:all -- --ci"
      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Drafts next Release notes
        if: matrix.is-main && github.event_name == 'push'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy to staging
      - name: Deploy to Firebase (Staging)
        if: matrix.is-main && github.event_name == 'push'
        run: |
          firebase use --add ddradar-staging
          firebase deploy --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: matrix.is-main && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: staging.ddradar.app
          commit_message: 'ci: auto deployment from'
