name: Node CI

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!**.md' # Exclude Markdown
  pull_request:
    paths:
      - '**'
      - '!**.md' # Exclude Markdown

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
        include:
          - node-version: 12
            is-main: true
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      - name: Use Cache # for optimize Install Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Install firestore Emulator
        run: |
          npm i -g firebase-tools
          npx firebase setup:emulators:firestore
      - name: Lint
        run: npm run lint
      - name: Build (Staging)
        run: npm run build
      - name: Run firestore Emulator & Test with Jest
        run: firebase emulators:exec --only firestore "npm run test:all -- --ci"
      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Drafts next Release notes
        if: matrix.is-main && github.event_name == 'push'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Firebase (Staging)
        if: matrix.is-main && github.event_name == 'push'
        run: |
          firebase use --add ddradar-staging
          firebase deploy --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to GitHub Pages
        if: matrix.is-main && github.event_name == 'push'
        run: |
          echo staging.ddradar.app > ./dist/CNAME
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
          bash ./entrypoint.sh
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
          INPUT_COMMITMESSAGE: 'ci: auto deployment from'
          INPUT_EMPTYCOMMITS: false
